const vaultCatalog = {

  /**
   * Vault upgrade groups by their index in the save file.
   */
  vaultGroupsByIndex: {

    100: {
      group: "Harmony",
      section: "Gameplay Section",
      alwaysUnlocked: true,
      upgrades: {
        1000: "Auto Restart Run",
        1010: "Ad Gem Stack",
        1020: "Damage Cap Slider",
        1030: "Global Presets",
      },
    },
    110: {
      group: "Harmony",
      section: "Cards Section",
      upgrades: {
        1200: "Additional Card Slot",
        1210: "Charge Berzerker",
        1220: "Demon Mode Automation",
        1230: "Smart Demon Mode Automation",
        1240: "Nuke Automation",
        1250: "Smart Nuke Automation",
        1260: "Death Ray Toggle",
        1270: "Spawn Accelerator Toggle",
        1280: "Life Saving Ordering",
        1290: "Energy Shield Restriction",

      },
    },
    120: {
      group: "Harmony",
      section: "UW Section",
      upgrades: {
        1400: "Missile Barrage Automation",
        1410: "Smart Missile Barrage Automation",
        1420: "Black Hole Size Slider",
        1430: "Swamp Range Slider",
      },
    },
    130: {
      group: "Harmony",
      section: "Modules Section",
      upgrades: {
        1600: "Auto Shatter Rare Modules",
        1610: "Daily Mission Shard Type",
        1620: "Free Mission Reroll",
        1630: "Module Reroll Discount",
        1640: "Module Presets",
      },
    },
    140: {
      group: "Harmony",
      section: "Bots Section",
      upgrades: {
        1800: "Bot Respec Discount",
        1805: "Bot Presets",
        1810: "Bot Range",
        1820: "Bot Cooldown Sliders",
      },
    },
    150: {
      group: "Harmony",
      section: "Workshop Section",
      upgrades: {
        2000: "Workshop Respec Discount",
        2005: "Workshop Presets",
        2010: "Enhancements Discount",
        2020: "Workshop Orb Adjuster",
      },
    },
    160: {
      group: "Harmony",
      section: "Guardian Section",
      upgrades: {
        2200: "Guardian Respec Discount",
        2205: "Guardian Presets",
      },
    },

    1000: {
      group: "Power",
      section: "Attack Section",
      upgrades: {
        1: "Damage",
        10: "Attack Speed",
        20: "Critical Chance",
        30: "Crit Factor",
        40: "Damage / Meter",
        50: "Multishot Chance",
        60: "Rapid Fire Chance",
        70: "Bounce Shot Chance",
        80: "Super Crit Chance",
        90: "Super Crit Mult",
        100: "Rend Armor Chance",
        110: "Rend Armor Mult",
      },
    },
    1010: {
      group: "Power",
      section: "Defense Section",
      upgrades: {
        200: "Health",
        210: "Health Regen",
        220: "Defense %",
        230: "Defense Absolute",
        240: "Thorn Damage",
        250: "Knockback Chance",
        260: "Knockback Force",
        270: "Orb Speed",
        280: "Orbs",
        290: "Shockwave Size",
        300: "Shockwave Frequency",
        310: "Death Defy",
        320: "Wall Health",
        330: "Wall Rebuild",
      },
    },
    1020: {
      group: "Power",
      section: "Utility Section",
      upgrades: {
        400: "Cash Bonus",
        410: "Cash / Wave",
        420: "Coins / Kill",
        430: "Coins / Wave",
        440: "Free Attack Upgrade",
        450: "Free Defense Upgrade",
        460: "Free Utility Upgrade",
        470: "Interest / Wave",
        480: "Recovery Amount",
        490: "Max Recovery",
        500: "Enemy Attack Skip",
        510: "Enemy Health Skip",
      },
    },
    1030: {
      group: "Power",
      section: "Ultimate Weapons Section",
      upgrades: {
        600: "Ultimate Damage",
        610: "Chain Lightning Damage",
        620: "Smart Missile Damage",
        630: "Death Wave Damage",
        640: "Inner Land Mine Damage",
        650: "Golden Tower Bonus",
        660: "Swamp Damage",
        670: "Spotlight Bonus",
        680: "Black Hole Size",
      },
    },

    2000: {
      group: "Enemy",
      section: "Simple Section",
      alwaysUnlocked: true,
      upgrades: {
        3000: "Basic Attack",
        3010: "Basic Health",
        3020: "Basic Coin Bonus",
        3100: "Fast Attack",
        3110: "Fast Health",
        3120: "Fast Speed",
        3200: "Tank Attack",
        3210: "Tank Health",
        3220: "Tank Mass",
      },
    },
    2010: {
      group: "Enemy",
      section: "Advanced Enemies Section",
      upgrades: {
        4000: "Boss Attack",
        4010: "Boss Health",
        4020: "Boss Common Drop Chance",
        4100: "Ranged Attack",
        4110: "Ranged Health",
        4120: "Ranged Attack Range",
        4200: "Protector Attack",
        4210: "Protector Health",
        4220: "Protector Radius",
      },
    },
    2020: {
      group: "Enemy",
      section: "Elites Enemies Section",
      upgrades: {
        5000: "Vampire Attack",
        5010: "Vampire Health",
        5020: "Vampire Attack Speed",
        5100: "Scatter Attack",
        5110: "Scatter Health",
        5120: "Scatter Attack Speed",
        5200: "Ray Attack",
        5210: "Ray Health",
        5220: "Ray Attack Speed",
      },
    },
    2030: {
      group: "Enemy",
      section: "Fleets Enemies Section",
      upgrades: {
        6000: "Saboteur Attack Speed",
        6010: "Saboteur Health",
        6020: "Saboteur Miss Chance",
        6100: "Commander Pulse Effect",
        6110: "Commander Health",
        6120: "Commander Pulse Speed",
        6200: "Overcharge Attack",
        6210: "Overcharge Health",
        6220: "Overcharge Attack Exponent",
      },
    },
  },
};
